services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Register Strategies
    App\Infrastructure\Strategy\TransCompanyStrategy:
        tags: ['app.shipping_strategy']

    App\Infrastructure\Strategy\PackGroupStrategy:
        tags: ['app.shipping_strategy']

    # Inject all strategies into the Service
    App\Application\ShippingService:
        arguments:
            $strategies: !tagged_iterator app.shipping_strategy
